<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Library_Borrowing_Tracker.Client</RootNamespace>
    <UserSecretsId>library-borrowing-tracker-client-member4</UserSecretsId>
  </PropertyGroup>

</Project>
